[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
pavex = { version = "0.1.25" }
tokio = { version = "1", features = ["full"] }
server_sdk = { path = "../server_sdk" }
app = { path = "../app" }

# Configuration
dotenvy = "0.15"
figment = { version = "0.10", features = ["env", "yaml"] }
serde = { version = "1", features = ["derive"] }

# Telemetry
pavex_tracing = { version = "0.1.25" }
tracing = "0.1"
tracing-bunyan-formatter = "0.3"
tracing-panic = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "registry", "smallvec", "std", "tracing-log"] }

[dev-dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1.0.116"
